# required for Travis-CI
branches:
  except:
    - gh-pages
sudo: false
language: node_js
node_js:
  - "0.12"
  - "4.2"
  - "5.4"
before_script:
  - npm install -g npm@latest && npm install -g grunt-cli
